name: FastAPI-Django

on:
  push:
    branches: [ "Mkadir" ]
  pull_request:
    branches: [ "Mkadir" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create Virtual Env
      run: |
        python3 -m venv venv
        source venv/bin/activate
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Collect statics
      run: |
        python manage.py collectstatic
    - name: Test for Demo App
      run: |
        uvicorn democore.asgi:app --host 0.0.0.0 --port 8080 --workers 1 --uds /tmp/uvicorn.sock &
        sleep 3
        kill %1
